---
kind: pipeline
name: commit
type: kubernetes

platform:
  os: linux
  arch: amd64

workspace:
  base: /workdir

steps:
- name: build_and_test_image
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/centos-base:latest
  #image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - yum update -y
  - yum install -y -q docker openssl wget
  - ./ci-build.sh
  environment:
    # DOCKER_HOST: tcp://172.17.0.1:2375
  when:
    event:
    - pull_request
    - push
    - tag

- name: push_image_to_artifactory
  pull: if-not-exists
  image: docker:17.12.0
  commands:
  - docker login -u="$${DOCKER_USERNAME}" -p="$${DOCKER_PASSWORD}" "$${DOCKER_REPO}"
  - ./publish.sh "ngx" "$${DOCKER_REPO}$${DOCKER_BASEDIR}$${DOCKER_IMAGE}" "$${DRONE_TAG}"
  environment:
    DOCKER_BASEDIR: /
    DOCKER_HOST: tcp://172.17.0.1:2375
    DOCKER_IMAGE: nginx-proxy
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_REPO: artifactory-internal.digital.homeoffice.gov.uk
    DOCKER_USERNAME: docker-nginx-proxy-robot
  when:
    event:
    - tag

- name: push_image_to_quay
  pull: if-not-exists
  image: docker:17.12.0
  commands:
  - docker login -u="$${DOCKER_USERNAME}" -p="$${DOCKER_QUAY_PASSWORD}" "$${DOCKER_REPO}"
  - ./publish.sh "ngx" "$${DOCKER_REPO}$${DOCKER_BASEDIR}$${DOCKER_IMAGE}" "$${DRONE_TAG}"
  environment:
    DOCKER_BASEDIR: /ukhomeofficedigital/
    DOCKER_HOST: tcp://172.17.0.1:2375
    DOCKER_IMAGE: nginx-proxy
    DOCKER_QUAY_PASSWORD:
      from_secret: docker_quay_password
    DOCKER_REPO: quay.io
    DOCKER_USERNAME: ukhomeofficedigital+nginx_proxy
  when:
    event:
    - tag

services:
- name: docker
  #image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  image: quay.io/ukhomeofficedigital/centos-base:latest

...
